In [12]:
from lol_spring_player_power import create_player_rankings
from lol_spring_player_power import df
from mid_season import create_mid_player_rankings
from mid_season import new_df

In [4]:
old_dfs=create_player_rankings(df)
old_dfs
old_top=old_dfs[0]

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py:3939: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(obj)
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/series.py:2994: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(result)

In [5]:
old_top

,Top [TSM Huni],Top [C9 Summit],Top [TL Bwipo],Top [100T Ssumday],Top [EG Impact],Top [GGS Licorice],Top [FLY Kumo],Top [CLG Jenkins],Top [IMT Revenge],Top [DIG FakeGod]
Name,,,,,,,,,,
Johann,4.0,1.0,2.0,5.0,3.0,8.0,10.0,7.0,6.0,9.0
Milad,4.0,1.0,2.0,5.0,3.0,6.0,10.0,9.0,7.0,8.0
Tak,4.0,1.0,2.0,8.0,3.0,5.0,10.0,6.0,9.0,7.0
Joimes,7.0,2.0,4.0,1.0,3.0,5.0,6.0,10.0,9.0,8.0
Zain,3.0,1.0,2.0,5.0,4.0,7.0,10.0,8.0,6.0,9.0
Average Rank,4.4,1.2,2.4,4.8,3.2,6.2,9.2,8.0,7.4,8.2
Highest,7.0,2.0,4.0,8.0,4.0,8.0,10.0,10.0,9.0,9.0
Lowest,3.0,1.0,2.0,1.0,3.0,5.0,6.0,6.0,6.0,7.0

In [10]:
x=old_top.loc['Average Rank']
x

Top [TSM Huni]        4.4
Top [C9 Summit]       1.2
Top [TL Bwipo]        2.4
Top [100T Ssumday]    4.8
Top [EG Impact]       3.2
Top [GGS Licorice]    6.2
Top [FLY Kumo]        9.2
Top [CLG Jenkins]     8.0
Top [IMT Revenge]     7.4
Top [DIG FakeGod]     8.2
Name: Average Rank, dtype: float64

In [13]:
new_dfs=create_mid_player_rankings(new_df)

|                    |   Johann |   Milad |   Tak |   Joimes |   Zain |   Kwan |   Average Rank |   Lowest |   Highest |
|:-------------------|---------:|--------:|------:|---------:|-------:|-------:|---------------:|---------:|----------:|
| Top [C9 Summit]    |        2 |       1 |     1 |        1 |      2 |      3 |        1.66667 |        3 |         1 |
| Top [TL Bwipo]     |        1 |       2 |     2 |        3 |      1 |      1 |        1.66667 |        3 |         1 |
| Top [100T Ssumday] |        4 |       3 |     4 |        4 |      3 |      2 |        3.33333 |        4 |         2 |
| Top [EG Impact]    |        3 |       4 |     3 |        2 |      4 |      6 |        3.66667 |        6 |         2 |
| Top [IMT Revenge]  |        5 |       5 |     6 |        6 |      5 |      8 |        5.83333 |        8 |         5 |
| Top [GGS Licorice] |        7 |       6 |     7 |        5 |     10 |      5 |        6.66667 |       10 |         5 |
| Top [TSM Huni]     |        6 |       8 |     5 |        7 |      8 |     10 |        7.33333 |       10 |         5 |
| Top [FLY Kumo]     |       10 |      10 |     9 |        8 |      7 |      4 |        8       |       10 |         4 |
| Top [CLG Jenkins]  |        8 |       7 |     8 |       10 |      9 |      7 |        8.16667 |       10 |         7 |
| Top [DIG FakeGod]  |        9 |       9 |    10 |        9 |      6 |      9 |        8.66667 |       10 |         6 |
|                           |   Johann |   Milad |   Tak |   Joimes |   Zain |   Kwan |   Average Rank |   Lowest |   Highest |
|:--------------------------|---------:|--------:|------:|---------:|-------:|-------:|---------------:|---------:|----------:|
| Jungle [C9 Blaber]        |        1 |       1 |     1 |        1 |      1 |      1 |        1       |        1 |         1 |
| Jungle [TL Santorin]      |        4 |       4 |     4 |        3 |      2 |      2 |        3.16667 |        4 |         2 |
| Jungle [100T Closer]      |        3 |       3 |     3 |        4 |      3 |      3 |        3.16667 |        4 |         3 |
| Jungle [EG Inspired]      |        2 |       2 |     2 |        2 |      6 |      8 |        3.66667 |        8 |         2 |
| Jungle [GGS Pridestalker] |        6 |       5 |     6 |        6 |      4 |      7 |        5.66667 |        7 |         4 |
| Jungle [TSM Spica]        |        7 |       8 |     5 |        5 |      7 |      6 |        6.33333 |        8 |         5 |
| Jungle [DIG River]        |        5 |       6 |     8 |        7 |      9 |      9 |        7.33333 |        9 |         5 |
| Jungle [FLY Josedeodo]    |        9 |       9 |     9 |        9 |      5 |      5 |        7.66667 |        9 |         5 |
| Jungle [IMT Xerxe]        |        8 |       7 |     7 |        8 |      8 |     10 |        8       |       10 |         7 |
| Jungle [CLG Contractz]    |       10 |      10 |    10 |       10 |     10 |      4 |        9       |       10 |         4 |
|                       |   Johann |   Milad |   Tak |   Joimes |   Zain |   Kwan |   Average Rank |   Lowest |   Highest |
|:----------------------|---------:|--------:|------:|---------:|-------:|-------:|---------------:|---------:|----------:|
| Mid [TL Bjergsen]     |        1 |       1 |     2 |        1 |      1 |      1 |        1.16667 |        2 |         1 |
| Mid [C9 Fudge]        |        4 |       3 |     1 |        3 |      2 |      2 |        2.5     |        4 |         1 |
| Mid [EG Jojopyun]     |        2 |       2 |     3 |        2 |      5 |      4 |        3       |        5 |         2 |
| Mid [100T Abbedagge]  |        3 |       4 |     4 |        4 |      3 |      3 |        3.5     |        4 |         3 |
| Mid [FLY Toucouille]  |        6 |       6 |     7 |        5 |      4 |      6 |        5.66667 |        7 |         4 |
| Mid [DIG Blue]        |        8 |       5 |     5 |        6 |      6 |      8 |        6.33333 |        8 |         5 |
| Mid [IMT POE]         |        5 |       8 |     9 |        7 |      7 |      7 |        7.16667 |        9 |         5 |
| Mid [GGS Ablazeolive] |        9 |       7 |     8 |        8 |      8 |      5 |        7.5     |        9 |         5 |
| Mid [TSM Keaiduo]     |        7 |       9 |     6 |        9 |     10 |     10 |        8.5     |       10 |         6 |
| Mid [CLG Palafox]     |       10 |      10 |    10 |       10 |      9 |      9 |        9.66667 |       10 |         9 |
|                              |   Johann |   Milad |   Tak |   Joimes |   Zain |   Kwan |   Average Rank |   Lowest |   Highest |
|:-----------------------------|---------:|--------:|------:|---------:|-------:|-------:|---------------:|---------:|----------:|
| ADC [C9 Berserker]           |        2 |       1 |     1 |        2 |      1 |      1 |        1.33333 |        2 |         1 |
| ADC [TL Hans Sama]           |        1 |       2 |     2 |        1 |      2 |      2 |        1.66667 |        2 |         1 |
| ADC [100T FBI]               |        4 |       3 |     3 |        4 |      6 |      3 |        3.83333 |        6 |         3 |
| ADC [EG Danny]               |        3 |       4 |     4 |        3 |      3 |      8 |        4.16667 |        8 |         3 |
| ADC [TSM Tactical]           |        5 |       6 |     5 |        6 |      7 |      7 |        6       |        7 |         5 |
| ADC [GGS Lost]               |        6 |       8 |     8 |        5 |      4 |      5 |        6       |        8 |         4 |
| ADC [DIG Neo]                |        7 |       5 |     6 |        8 |      8 |      9 |        7.16667 |        9 |         5 |
| ADC [FLY Johnsun]            |       10 |      10 |     7 |        9 |      5 |      4 |        7.5     |       10 |         4 |
| ADC [IMT Wildturtle / Arrow] |        8 |       7 |     9 |        7 |     10 |     10 |        8.5     |       10 |         7 |
| ADC [CLG Luger]              |        9 |       9 |    10 |       10 |      9 |      6 |        8.83333 |       10 |         6 |
|                           |   Johann |   Milad |   Tak |   Joimes |   Zain |   Kwan |   Average Rank |   Lowest |   Highest |
|:--------------------------|---------:|--------:|------:|---------:|-------:|-------:|---------------:|---------:|----------:|
| SUP [TL CoreJJ]           |        1 |       1 |     1 |        1 |      1 |      1 |        1       |        1 |         1 |
| SUP [EG Vulcan]           |        2 |       2 |     2 |        2 |      3 |      4 |        2.5     |        4 |         2 |
| SUP [100T Huhi]           |        3 |       4 |     3 |        3 |      5 |      2 |        3.33333 |        5 |         2 |
| SUP [C9 Winsome]          |        5 |       5 |     4 |        4 |      2 |      3 |        3.83333 |        5 |         2 |
| SUP [FLY Aphromoo]        |        4 |       3 |     5 |        5 |      4 |      8 |        4.83333 |        8 |         3 |
| SUP [GGS Olleh]           |        7 |       6 |     6 |        6 |      7 |      6 |        6.33333 |        7 |         6 |
| SUP [DIG Biofrost]        |        6 |       7 |     7 |        7 |      8 |      5 |        6.66667 |        8 |         5 |
| SUP [TSM Shenyi / Yursan] |        8 |       8 |     8 |        9 |     10 |     10 |        8.83333 |       10 |         8 |
| SUP [CLG Poome]           |        9 |       9 |     9 |       10 |      9 |      7 |        8.83333 |       10 |         7 |
| SUP [IMT Destiny]         |       10 |      10 |    10 |        8 |      6 |      9 |        8.83333 |       10 |         6 |

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py:3939: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(obj)
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/series.py:2994: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(result)

In [14]:
new_dfs

[              Top [TSM Huni]  Top [C9 Summit]  Top [TL Bwipo]  \
 Name
 Johann              6.000000         2.000000        1.000000
 Milad               8.000000         1.000000        2.000000
 Tak                 5.000000         1.000000        2.000000
 Joimes              7.000000         1.000000        3.000000
 Zain                8.000000         2.000000        1.000000
 Kwan               10.000000         3.000000        1.000000
 Average Rank        7.333333         1.666667        1.666667
 Lowest             10.000000         3.000000        3.000000
 Highest             5.000000         1.000000        1.000000

               Top [100T Ssumday]  Top [EG Impact]  Top [GGS Licorice]  \
 Name
 Johann                  4.000000         3.000000            7.000000
 Milad                   3.000000         4.000000            6.000000
 Tak                     4.000000         3.000000            7.000000
 Joimes                  4.000000         2.000000            5.000000
 Zain                    3.000000         4.000000           10.000000
 Kwan                    2.000000         6.000000            5.000000
 Average Rank            3.333333         3.666667            6.666667
 Lowest                  4.000000         6.000000           10.000000
 Highest                 2.000000         2.000000            5.000000

               Top [FLY Kumo]  Top [CLG Jenkins]  Top [IMT Revenge]  \
 Name
 Johann                  10.0           8.000000           5.000000
 Milad                   10.0           7.000000           5.000000
 Tak                      9.0           8.000000           6.000000
 Joimes                   8.0          10.000000           6.000000
 Zain                     7.0           9.000000           5.000000
 Kwan                     4.0           7.000000           8.000000
 Average Rank             8.0           8.166667           5.833333
 Lowest                  10.0          10.000000           8.000000
 Highest                  4.0           7.000000           5.000000

               Top [DIG FakeGod]
 Name
 Johann                 9.000000
 Milad                  9.000000
 Tak                   10.000000
 Joimes                 9.000000
 Zain                   6.000000
 Kwan                   9.000000
 Average Rank           8.666667
 Lowest                10.000000
 Highest                6.000000  ,
               Jungle [TSM Spica]  Jungle [C9 Blaber]  Jungle [TL Santorin]  \
 Name
 Johann                  7.000000                 1.0              4.000000
 Milad                   8.000000                 1.0              4.000000
 Tak                     5.000000                 1.0              4.000000
 Joimes                  5.000000                 1.0              3.000000
 Zain                    7.000000                 1.0              2.000000
 Kwan                    6.000000                 1.0              2.000000
 Average Rank            6.333333                 1.0              3.166667
 Lowest                  8.000000                 1.0              4.000000
 Highest                 5.000000                 1.0              2.000000

               Jungle [100T Closer]  Jungle [EG Inspired]  \
 Name
 Johann                    3.000000              2.000000
 Milad                     3.000000              2.000000
 Tak                       3.000000              2.000000
 Joimes                    4.000000              2.000000
 Zain                      3.000000              6.000000
 Kwan                      3.000000              8.000000
 Average Rank              3.166667              3.666667
 Lowest                    4.000000              8.000000
 Highest                   3.000000              2.000000

               Jungle [GGS Pridestalker]  Jungle [FLY Josedeodo]  \
 Name
 Johann                         6.000000                9.000000
 Milad                          5.000000                9.000000
 Tak                            6.000000                9.000000
 Joimes                         6.000000                9.000000
 Zain                           4.000000                5.000000
 Kwan                           7.000000                5.000000
 Average Rank                   5.666667                7.666667
 Lowest                         7.000000                9.000000
 Highest                        4.000000                5.000000

               Jungle [CLG Contractz]  Jungle [IMT Xerxe]  Jungle [DIG River]
 Name
 Johann                          10.0                 8.0            5.000000
 Milad                           10.0                 7.0            6.000000
 Tak                             10.0                 7.0            8.000000
 Joimes                          10.0                 8.0            7.000000
 Zain                            10.0                 8.0            9.000000
 Kwan                             4.0                10.0            9.000000
 Average Rank                     9.0                 8.0            7.333333
 Lowest                          10.0                10.0            9.000000
 Highest                          4.0                 7.0            5.000000  ,
               Mid [TSM Keaiduo]  Mid [C9 Fudge]  Mid [TL Bjergsen]  \
 Name
 Johann                      7.0             4.0           1.000000
 Milad                       9.0             3.0           1.000000
 Tak                         6.0             1.0           2.000000
 Joimes                      9.0             3.0           1.000000
 Zain                       10.0             2.0           1.000000
 Kwan                       10.0             2.0           1.000000
 Average Rank                8.5             2.5           1.166667
 Lowest                     10.0             4.0           2.000000
 Highest                     6.0             1.0           1.000000

               Mid [100T Abbedagge]  Mid [EG Jojopyun]  Mid [GGS Ablazeolive]  \
 Name
 Johann                         3.0                2.0                    9.0
 Milad                          4.0                2.0                    7.0
 Tak                            4.0                3.0                    8.0
 Joimes                         4.0                2.0                    8.0
 Zain                           3.0                5.0                    8.0
 Kwan                           3.0                4.0                    5.0
 Average Rank                   3.5                3.0                    7.5
 Lowest                         4.0                5.0                    9.0
 Highest                        3.0                2.0                    5.0

               Mid [FLY Toucouille]  Mid [CLG Palafox]  Mid [IMT POE]  \
 Name
 Johann                    6.000000          10.000000       5.000000
 Milad                     6.000000          10.000000       8.000000
 Tak                       7.000000          10.000000       9.000000
 Joimes                    5.000000          10.000000       7.000000
 Zain                      4.000000           9.000000       7.000000
 Kwan                      6.000000           9.000000       7.000000
 Average Rank              5.666667           9.666667       7.166667
 Lowest                    7.000000          10.000000       9.000000
 Highest                   4.000000           9.000000       5.000000

               Mid [DIG Blue]
 Name
 Johann              8.000000
 Milad               5.000000
 Tak                 5.000000
 Joimes              6.000000
 Zain                6.000000
 Kwan                8.000000
 Average Rank        6.333333
 Lowest              8.000000
 Highest             5.000000  ,
               ADC [TSM Tactical]  ADC [C9 Berserker]  ADC [TL Hans Sama]  \
 Name
 Johann                       5.0            2.000000            1.000000
 Milad                        6.0            1.000000            2.000000
 Tak                          5.0            1.000000            2.000000
 Joimes                       6.0            2.000000            1.000000
 Zain                         7.0            1.000000            2.000000
 Kwan                         7.0            1.000000            2.000000
 Average Rank                 6.0            1.333333            1.666667
 Lowest                       7.0            2.000000            2.000000
 Highest                      5.0            1.000000            1.000000

               ADC [100T FBI]  ADC [EG Danny]  ADC [GGS Lost]  \
 Name
 Johann              4.000000        3.000000             6.0
 Milad               3.000000        4.000000             8.0
 Tak                 3.000000        4.000000             8.0
 Joimes              4.000000        3.000000             5.0
 Zain                6.000000        3.000000             4.0
 Kwan                3.000000        8.000000             5.0
 Average Rank        3.833333        4.166667             6.0
 Lowest              6.000000        8.000000             8.0
 Highest             3.000000        3.000000             4.0

               ADC [FLY Johnsun]  ADC [CLG Luger]  \
 Name
 Johann                     10.0         9.000000
 Milad                      10.0         9.000000
 Tak                         7.0        10.000000
 Joimes                      9.0        10.000000
 Zain                        5.0         9.000000
 Kwan                        4.0         6.000000
 Average Rank                7.5         8.833333
 Lowest                     10.0        10.000000
 Highest                     4.0         6.000000

               ADC [IMT Wildturtle / Arrow]  ADC [DIG Neo]
 Name
 Johann                                 8.0       7.000000
 Milad                                  7.0       5.000000
 Tak                                    9.0       6.000000
 Joimes                                 7.0       8.000000
 Zain                                  10.0       8.000000
 Kwan                                  10.0       9.000000
 Average Rank                           8.5       7.166667
 Lowest                                10.0       9.000000
 Highest                                7.0       5.000000  ,
               SUP [TSM Shenyi / Yursan]  SUP [C9 Winsome]  SUP [TL CoreJJ]  \
 Name
 Johann                         8.000000          5.000000              1.0
 Milad                          8.000000          5.000000              1.0
 Tak                            8.000000          4.000000              1.0
 Joimes                         9.000000          4.000000              1.0
 Zain                          10.000000          2.000000              1.0
 Kwan                          10.000000          3.000000              1.0
 Average Rank                   8.833333          3.833333              1.0
 Lowest                        10.000000          5.000000              1.0
 Highest                        8.000000          2.000000              1.0

               SUP [100T Huhi]  SUP [EG Vulcan]  SUP [GGS Olleh]  \
 Name
 Johann               3.000000              2.0         7.000000
 Milad                4.000000              2.0         6.000000
 Tak                  3.000000              2.0         6.000000
 Joimes               3.000000              2.0         6.000000
 Zain                 5.000000              3.0         7.000000
 Kwan                 2.000000              4.0         6.000000
 Average Rank         3.333333              2.5         6.333333
 Lowest               5.000000              4.0         7.000000
 Highest              2.000000              2.0         6.000000

               SUP [FLY Aphromoo]  SUP [CLG Poome]  SUP [IMT Destiny]  \
 Name
 Johann                  4.000000         9.000000          10.000000
 Milad                   3.000000         9.000000          10.000000
 Tak                     5.000000         9.000000          10.000000
 Joimes                  5.000000        10.000000           8.000000
 Zain                    4.000000         9.000000           6.000000
 Kwan                    8.000000         7.000000           9.000000
 Average Rank            4.833333         8.833333           8.833333
 Lowest                  8.000000        10.000000          10.000000
 Highest                 3.000000         7.000000           6.000000

               SUP [DIG Biofrost]
 Name
 Johann                  6.000000
 Milad                   7.000000
 Tak                     7.000000
 Joimes                  7.000000
 Zain                    8.000000
 Kwan                    5.000000
 Average Rank            6.666667
 Lowest                  8.000000
 Highest                 5.000000  ]

In [16]:
new_dfs[0]
new_top=new_dfs[0]

In [21]:
new_top=new_top.round(1)
new_top

,Top [TSM Huni],Top [C9 Summit],Top [TL Bwipo],Top [100T Ssumday],Top [EG Impact],Top [GGS Licorice],Top [FLY Kumo],Top [CLG Jenkins],Top [IMT Revenge],Top [DIG FakeGod]
Name,,,,,,,,,,
Johann,6.0,2.0,1.0,4.0,3.0,7.0,10.0,8.0,5.0,9.0
Milad,8.0,1.0,2.0,3.0,4.0,6.0,10.0,7.0,5.0,9.0
Tak,5.0,1.0,2.0,4.0,3.0,7.0,9.0,8.0,6.0,10.0
Joimes,7.0,1.0,3.0,4.0,2.0,5.0,8.0,10.0,6.0,9.0
Zain,8.0,2.0,1.0,3.0,4.0,10.0,7.0,9.0,5.0,6.0
Kwan,10.0,3.0,1.0,2.0,6.0,5.0,4.0,7.0,8.0,9.0
Average Rank,7.3,1.7,1.7,3.3,3.7,6.7,8.0,8.2,5.8,8.7
Lowest,10.0,3.0,3.0,4.0,6.0,10.0,10.0,10.0,8.0,10.0
Highest,5.0,1.0,1.0,2.0,2.0,5.0,4.0,7.0,5.0,6.0

In [18]:
old_top

,Top [TSM Huni],Top [C9 Summit],Top [TL Bwipo],Top [100T Ssumday],Top [EG Impact],Top [GGS Licorice],Top [FLY Kumo],Top [CLG Jenkins],Top [IMT Revenge],Top [DIG FakeGod]
Name,,,,,,,,,,
Johann,4.0,1.0,2.0,5.0,3.0,8.0,10.0,7.0,6.0,9.0
Milad,4.0,1.0,2.0,5.0,3.0,6.0,10.0,9.0,7.0,8.0
Tak,4.0,1.0,2.0,8.0,3.0,5.0,10.0,6.0,9.0,7.0
Joimes,7.0,2.0,4.0,1.0,3.0,5.0,6.0,10.0,9.0,8.0
Zain,3.0,1.0,2.0,5.0,4.0,7.0,10.0,8.0,6.0,9.0
Average Rank,4.4,1.2,2.4,4.8,3.2,6.2,9.2,8.0,7.4,8.2
Highest,7.0,2.0,4.0,8.0,4.0,8.0,10.0,10.0,9.0,9.0
Lowest,3.0,1.0,2.0,1.0,3.0,5.0,6.0,6.0,6.0,7.0

In [22]:
test_diff=new_top.loc['Average Rank']-old_top.loc['Average Rank']

In [23]:
test_diff

Top [TSM Huni]        2.9
Top [C9 Summit]       0.5
Top [TL Bwipo]       -0.7
Top [100T Ssumday]   -1.5
Top [EG Impact]       0.5
Top [GGS Licorice]    0.5
Top [FLY Kumo]       -1.2
Top [CLG Jenkins]     0.2
Top [IMT Revenge]    -1.6
Top [DIG FakeGod]     0.5
Name: Average Rank, dtype: float64

In [27]:
old_dfs[0].loc['Average Rank']

Top [TSM Huni]        4.4
Top [C9 Summit]       1.2
Top [TL Bwipo]        2.4
Top [100T Ssumday]    4.8
Top [EG Impact]       3.2
Top [GGS Licorice]    6.2
Top [FLY Kumo]        9.2
Top [CLG Jenkins]     8.0
Top [IMT Revenge]     7.4
Top [DIG FakeGod]     8.2
Name: Average Rank, dtype: float64